/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OkParticleTrail {
    }
}
declare global {
    interface HTMLOkParticleTrailElement extends Components.OkParticleTrail, HTMLStencilElement {
    }
    var HTMLOkParticleTrailElement: {
        prototype: HTMLOkParticleTrailElement;
        new (): HTMLOkParticleTrailElement;
    };
    interface HTMLElementTagNameMap {
        "ok-particle-trail": HTMLOkParticleTrailElement;
    }
}
declare namespace LocalJSX {
    interface OkParticleTrail {
    }
    interface IntrinsicElements {
        "ok-particle-trail": OkParticleTrail;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ok-particle-trail": LocalJSX.OkParticleTrail & JSXBase.HTMLAttributes<HTMLOkParticleTrailElement>;
        }
    }
}
